// <auto-generated />
using System;
using AppraisalTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppraisalTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240729155817_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppraisalTracker.Modules.AppraisalActivity.Models.Implementation", b =>
                {
                    b.Property<int>("ImplementationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImplementationId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MeasurableActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("Stakeholder")
                        .HasColumnType("text");

                    b.HasKey("ImplementationId");

                    b.HasIndex("MeasurableActivityId");

                    b.ToTable("Implementations");
                });

            modelBuilder.Entity("AppraisalTracker.Modules.AppraisalActivity.Models.MeasurableActivity", b =>
                {
                    b.Property<int>("MeasurableActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurableActivityId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Initiative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perspective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SsMartaObjectives")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeasurableActivityId");

                    b.ToTable("MeasurableActivities");
                });

            modelBuilder.Entity("AppraisalTracker.Modules.AppraisalActivity.Models.Implementation", b =>
                {
                    b.HasOne("AppraisalTracker.Modules.AppraisalActivity.Models.MeasurableActivity", "MeasurableActivity")
                        .WithMany("Implementation")
                        .HasForeignKey("MeasurableActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurableActivity");
                });

            modelBuilder.Entity("AppraisalTracker.Modules.AppraisalActivity.Models.MeasurableActivity", b =>
                {
                    b.Navigation("Implementation");
                });
#pragma warning restore 612, 618
        }
    }
}
